-- Gate 10 (migration validation) applies this from scratch on every integration-test
-- run. Gate 9's backend ratchet guard checks that this directory is never empty and
-- that no two migrations share a version number.
CREATE TABLE items (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    done  BOOLEAN NOT NULL DEFAULT FALSE
);
